<?php

define("ERROR_COOK_NOT_CODE",ERROR_COOK | 0x0001);
define("ERROR_COOK_CODE_EXISTS",ERROR_COOK | 0x0002);
define("ERROR_COOK_NOT_TITLE",ERROR_COOK | 0x0003);
define("ERROR_COOK_TITLE_EXISTS",ERROR_COOK | 0x0004);
define("ERROR_COOK_NOT_FOUND_CHEF",ERROR_COOK | 0x0005);
define("ERROR_COOK_NOT_FOUND_PACKAGE",ERROR_COOK | 0x0006);
define("ERROR_COOK_NOT_FOUND_ORDERDAY",ERROR_COOK | 0x0007);
define("ERROR_COOK_NOT_FOUND_ORDERMEAL",ERROR_COOK | 0x0008);
define("ERROR_COOK_NOT_FOUND_CITY",ERROR_COOK | 0x0009);
define("ERROR_COOK_NOT_FOUND_AREA",ERROR_COOK | 0x000a);
define("ERROR_COOK_NOT_FOUND_ADDRESS",ERROR_COOK | 0x000b);
define("ERROR_COOK_NOT_FOUND_NAME",ERROR_COOK | 0x000c);
define("ERROR_COOK_NOT_FOUND_PHONE",ERROR_COOK | 0x000d);
define("ERROR_COOK_CREATE_ORDER",ERROR_COOK | 0x000e);
define("ERROR_COOK_ORDER_STATUS",ERROR_COOK | 0x000f);

class COException extends Exception{
	
}
?>